# Generated by Django 4.1.7 on 2023-02-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnum_1', models.CharField(max_length=20)),
                ('rollnum_2', models.CharField(max_length=20)),
                ('name_1', models.CharField(max_length=100)),
                ('name_2', models.CharField(max_length=100)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('h_num', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hostel_no', models.IntegerField(max_length=2)),
                ('room_no', models.IntegerField(max_length=3)),
                ('hostel_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelentryexit.hostel')),
            ],
        ),
    ]
