# Generated by Django 4.1.7 on 2023-02-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='out_time',
        ),
    ]
