# Generated by Django 4.1.7 on 2023-02-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0002_hostel_h_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='h_num',
            field=models.CharField(max_length=4),
        ),
    ]
