# Generated by Django 4.1.7 on 2023-03-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0003_database_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hostel_visited',
        ),
    ]
