# Generated by Django 4.1.7 on 2023-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0004_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20)),
                ('hostel_no', models.IntegerField(max_length=2)),
                ('room_no', models.IntegerField(max_length=3)),
                ('hostelvisited', models.IntegerField(max_length=2)),
            ],
        ),
    ]
