# Generated by Django 4.1.7 on 2023-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0004_remove_users_hostel_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
