# Generated by Django 4.1.7 on 2023-03-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0005_users_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='image',
            new_name='student_image',
        ),
    ]
