# Generated by Django 4.1.7 on 2023-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0005_alter_database_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='out_time',
            field=models.BooleanField(default=False),
        ),
    ]
