# Generated by Django 4.1.7 on 2023-02-28 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0006_alter_database_rollnum_1_alter_database_rollnum_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='in_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 28, 13, 48, 5, 281628)),
        ),
    ]
