# Generated by Django 4.1.7 on 2023-02-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0006_alter_database_rollnum_1_alter_database_rollnum_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='users',
            field=models.ManyToManyField(to='hostelentryexit.users'),
        ),
    ]
