# Generated by Django 4.1.7 on 2023-02-28 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0007_alter_database_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='in_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 28, 14, 0, 15, 618763)),
        ),
    ]
