# Generated by Django 4.1.7 on 2023-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0007_alter_database_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='h_num',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
