# Generated by Django 4.1.7 on 2023-02-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0007_hostel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='users',
        ),
        migrations.AddField(
            model_name='users',
            name='hostel_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostelentryexit.hostel'),
            preserve_default=False,
        ),
    ]
