# Generated by Django 4.1.7 on 2023-02-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0008_remove_hostel_users_users_hostel_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='hostel_num',
            new_name='hostel_visited',
        ),
        migrations.RemoveField(
            model_name='users',
            name='hostelvisited',
        ),
    ]
