# Generated by Django 4.1.7 on 2023-03-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0008_alter_hostel_h_num_alter_hostel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnum_1', models.CharField(max_length=20)),
                ('rollnum_2', models.CharField(max_length=20)),
                ('name_1', models.CharField(max_length=100)),
                ('name_2', models.CharField(max_length=100)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='database',
            name='in_time',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='out_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
