# Generated by Django 4.1.7 on 2023-03-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0009_tempdata_alter_database_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='rollnum_1',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
