# Generated by Django 4.1.7 on 2023-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0010_remove_tempdata_id_alter_tempdata_rollnum_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='hnum_1',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='hnum_2',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempdata',
            name='hnum_1',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempdata',
            name='hnum_2',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
