# Generated by Django 4.1.7 on 2023-03-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelentryexit', '0011_database_hnum_1_database_hnum_2_tempdata_hnum_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='hnum_1',
            new_name='h_num',
        ),
        migrations.RenameField(
            model_name='tempdata',
            old_name='hnum_1',
            new_name='h_num',
        ),
        migrations.RemoveField(
            model_name='database',
            name='hnum_2',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='hnum_2',
        ),
    ]
