# Generated by Django 4.1.7 on 2023-02-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
