# Generated by Django 4.1.7 on 2023-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='images',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
